/* tslint:disable */
/* eslint-disable */
/**
 * Blackfinch.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLoanApplicationRequest
 */
export interface CreateLoanApplicationRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateLoanApplicationRequest
     */
    loanAmountPence?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLoanApplicationRequest
     */
    assetValuePence?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLoanApplicationRequest
     */
    creditScore?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLoanApplicationRequest
     */
    readonly loanToValuePercent?: number;
}

/**
 * Check if a given object implements the CreateLoanApplicationRequest interface.
 */
export function instanceOfCreateLoanApplicationRequest(value: object): value is CreateLoanApplicationRequest {
    return true;
}

export function CreateLoanApplicationRequestFromJSON(json: any): CreateLoanApplicationRequest {
    return CreateLoanApplicationRequestFromJSONTyped(json, false);
}

export function CreateLoanApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLoanApplicationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'loanAmountPence': json['loanAmountPence'] == null ? undefined : json['loanAmountPence'],
        'assetValuePence': json['assetValuePence'] == null ? undefined : json['assetValuePence'],
        'creditScore': json['creditScore'] == null ? undefined : json['creditScore'],
        'loanToValuePercent': json['loanToValuePercent'] == null ? undefined : json['loanToValuePercent'],
    };
}

export function CreateLoanApplicationRequestToJSON(json: any): CreateLoanApplicationRequest {
    return CreateLoanApplicationRequestToJSONTyped(json, false);
}

export function CreateLoanApplicationRequestToJSONTyped(value?: Omit<CreateLoanApplicationRequest, 'loanToValuePercent'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loanAmountPence': value['loanAmountPence'],
        'assetValuePence': value['assetValuePence'],
        'creditScore': value['creditScore'],
    };
}

