/* tslint:disable */
/* eslint-disable */
/**
 * Blackfinch.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoanTotalApplicantsGet200Response
 */
export interface LoanTotalApplicantsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof LoanTotalApplicantsGet200Response
     */
    declined?: number;
    /**
     * 
     * @type {number}
     * @memberof LoanTotalApplicantsGet200Response
     */
    approved?: number;
}

/**
 * Check if a given object implements the LoanTotalApplicantsGet200Response interface.
 */
export function instanceOfLoanTotalApplicantsGet200Response(value: object): value is LoanTotalApplicantsGet200Response {
    return true;
}

export function LoanTotalApplicantsGet200ResponseFromJSON(json: any): LoanTotalApplicantsGet200Response {
    return LoanTotalApplicantsGet200ResponseFromJSONTyped(json, false);
}

export function LoanTotalApplicantsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanTotalApplicantsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'declined': json['Declined'] == null ? undefined : json['Declined'],
        'approved': json['Approved'] == null ? undefined : json['Approved'],
    };
}

export function LoanTotalApplicantsGet200ResponseToJSON(json: any): LoanTotalApplicantsGet200Response {
    return LoanTotalApplicantsGet200ResponseToJSONTyped(json, false);
}

export function LoanTotalApplicantsGet200ResponseToJSONTyped(value?: LoanTotalApplicantsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Declined': value['declined'],
        'Approved': value['approved'],
    };
}

