/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotalValueRouteImport } from './routes/total-value'
import { Route as TotalApplicantsRouteImport } from './routes/total-applicants'
import { Route as MeanLtvRouteImport } from './routes/mean-ltv'
import { Route as IndexRouteImport } from './routes/index'

const TotalValueRoute = TotalValueRouteImport.update({
  id: '/total-value',
  path: '/total-value',
  getParentRoute: () => rootRouteImport,
} as any)
const TotalApplicantsRoute = TotalApplicantsRouteImport.update({
  id: '/total-applicants',
  path: '/total-applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const MeanLtvRoute = MeanLtvRouteImport.update({
  id: '/mean-ltv',
  path: '/mean-ltv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mean-ltv': typeof MeanLtvRoute
  '/total-applicants': typeof TotalApplicantsRoute
  '/total-value': typeof TotalValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mean-ltv': typeof MeanLtvRoute
  '/total-applicants': typeof TotalApplicantsRoute
  '/total-value': typeof TotalValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mean-ltv': typeof MeanLtvRoute
  '/total-applicants': typeof TotalApplicantsRoute
  '/total-value': typeof TotalValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mean-ltv' | '/total-applicants' | '/total-value'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mean-ltv' | '/total-applicants' | '/total-value'
  id: '__root__' | '/' | '/mean-ltv' | '/total-applicants' | '/total-value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeanLtvRoute: typeof MeanLtvRoute
  TotalApplicantsRoute: typeof TotalApplicantsRoute
  TotalValueRoute: typeof TotalValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/total-value': {
      id: '/total-value'
      path: '/total-value'
      fullPath: '/total-value'
      preLoaderRoute: typeof TotalValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/total-applicants': {
      id: '/total-applicants'
      path: '/total-applicants'
      fullPath: '/total-applicants'
      preLoaderRoute: typeof TotalApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mean-ltv': {
      id: '/mean-ltv'
      path: '/mean-ltv'
      fullPath: '/mean-ltv'
      preLoaderRoute: typeof MeanLtvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeanLtvRoute: MeanLtvRoute,
  TotalApplicantsRoute: TotalApplicantsRoute,
  TotalValueRoute: TotalValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
